package proteins

class Codons {

  def codonToAmino(codon:String ) = {
    codon match  {
      case "UUU" => new AminoAcid(codon,"Phenylalanine"	, "Phe" ,"F")
      case "UUC" => new AminoAcid(codon,"Phenylalanine"	, "Phe" ,"F")
      case "UUA" => new AminoAcid(codon,"Leucine	     ", "Leu" ,"L")
      case "UUG" => new AminoAcid(codon,"Leucine	     ", "Leu" ,"L")
      case "UCU" => new AminoAcid(codon,"Serine	       ", "Ser" ,"S")
      case "UCC" => new AminoAcid(codon,"Serine	       ", "Ser" ,"S")
      case "UCA" => new AminoAcid(codon,"Serine	       ", "Ser" ,"S")
      case "UCG" => new AminoAcid(codon,"Serine	       ", "Ser" ,"S")
      case "UAU" => new AminoAcid(codon,"Tyrosine	     ", "Tyr" ,"Y")
      case "UAC" => new AminoAcid(codon,"Tyrosine	     ", "Tyr" ,"Y")
      case "UAA" => new AminoAcid(codon,"Termination (ochre)", "XXX" ," "	)
      case "UAG" => new AminoAcid(codon,"Termination (amber)", "XXX" ," "	)
      case "UGU" => new AminoAcid(codon,"Cysteine	     ", "Cys" ,"C")
      case "UGC" => new AminoAcid(codon,"Cysteine	     ", "Cys" ,"C")
      case "UGA" => new AminoAcid(codon,"Termination (opal or umber)", "XXX" ," ")
      case "UGG" => new AminoAcid(codon,"Tryptophan	   ", "Trp" ,"W")
      case "CUU" => new AminoAcid(codon,"Leucine	     ", "Leu" ,"L")
      case "CUC" => new AminoAcid(codon,"Leucine	     ", "Leu" ,"L")
      case "CUA" => new AminoAcid(codon,"Leucine	     ", "Leu" ,"L")
      case "CUG" => new AminoAcid(codon,"Leucine	     ", "Leu" ,"L")
      case "CCU" => new AminoAcid(codon,"Proline	     ", "Pro" ,"P")
      case "CCC" => new AminoAcid(codon,"Proline	     ", "Pro" ,"P")
      case "CCA" => new AminoAcid(codon,"Proline	     ", "Pro" ,"P")
      case "CCG" => new AminoAcid(codon,"Proline	     ", "Pro" ,"P")
      case "CAU" => new AminoAcid(codon,"Histidine	   ", "His" ,"H")
      case "CAC" => new AminoAcid(codon,"Histidine	   ", "His" ,"H")
      case "CAA" => new AminoAcid(codon,"Glutamine	   ", "Gln" ,"Q")
      case "CAG" => new AminoAcid(codon,"Glutamine	   ", "Gln" ,"Q")
      case "CGU" => new AminoAcid(codon,"Arginine	     ", "Arg" ,"R")
      case "CGC" => new AminoAcid(codon,"Arginine	     ", "Arg" ,"R")
      case "CGA" => new AminoAcid(codon,"Arginine	     ", "Arg" ,"R")
      case "CGG" => new AminoAcid(codon,"Arginine	     ", "Arg" ,"R")
      case "AUU" => new AminoAcid(codon,"Isoleucine	   ", "Ile" ,"I")
      case "AUC" => new AminoAcid(codon,"Isoleucine	   ", "Ile" ,"I")
      case "AUA" => new AminoAcid(codon,"Isoleucine	   ", "Ile" ,"I")
      case "AUG" => new AminoAcid(codon,"Methionine	   ", "Met" ,"M")
      case "ACU" => new AminoAcid(codon,"Threoninef	   ", "Thr" ,"T")
      case "ACC" => new AminoAcid(codon,"Threonine	   ", "Thr" ,"T")
      case "ACA" => new AminoAcid(codon,"Threonine	   ", "Thr" ,"T")
      case "ACG" => new AminoAcid(codon,"Threonine	   ", "Thr" ,"T")
      case "AAU" => new AminoAcid(codon,"Asparagine	   ", "Asn" ,"N")
      case "AAC" => new AminoAcid(codon,"Asparagine	   ", "Asn" ,"N")
      case "AAA" => new AminoAcid(codon,"Lysine	       ", "Lys" ,"K")
      case "AAG" => new AminoAcid(codon,"Lysine	       ", "Lys" ,"K")
      case "AGU" => new AminoAcid(codon,"Serine	       ", "Ser" ,"S")
      case "AGC" => new AminoAcid(codon,"Serine	       ", "Ser" ,"S")
      case "AGA" => new AminoAcid(codon,"Arginine	     ", "Arg" ,"R")
      case "AGG" => new AminoAcid(codon,"Arginine	     ", "Arg" ,"R")
      case "GUU" => new AminoAcid(codon,"Valine	       ", "Val" ,"V")
      case "GUC" => new AminoAcid(codon,"Valine	       ", "Val" ,"V")
      case "GUA" => new AminoAcid(codon,"Valine	       ", "Val" ,"V")
      case "GUG" => new AminoAcid(codon,"Valine	       ", "Val" ,"V")
      case "GCU" => new AminoAcid(codon,"Alanine	     ", "Ala" ,"A")
      case "GCC" => new AminoAcid(codon,"Alanine	     ", "Ala" ,"A")
      case "GCA" => new AminoAcid(codon,"Alanine	     ", "Ala" ,"A")
      case "GCG" => new AminoAcid(codon,"Alanine	     ", "Ala" ,"A")
      case "GAU" => new AminoAcid(codon,"Aspartate	   ", "Asp" ,"D")
      case "GAC" => new AminoAcid(codon,"Aspartate	   ", "Asp" ,"D")
      case "GAA" => new AminoAcid(codon,"Glutamate	   ", "Glu" ,"E")
      case "GAG" => new AminoAcid(codon,"Glutamate	   ", "Glu" ,"E")
      case "GGU" => new AminoAcid(codon,"Glycine	     ", "Gly" ,"G")
      case "GGC" => new AminoAcid(codon,"Glycine	     ", "Gly" ,"G")
      case "GGA" => new AminoAcid(codon,"Glycine	     ", "Gly" ,"G")
      case "GGG" => new AminoAcid(codon,"Glycine	     ", "Gly" ,"G")
    }
  }
}
