import com.sun.xml.internal.ws.util.StringUtils;
import org.assertj.core.data.Offset;
import org.junit.Test;

import java.math.BigDecimal;
import java.util.HashMap;
import java.util.Map;

import static org.apache.commons.lang3.StringUtils.*;
import static org.assertj.core.api.Assertions.assertThat;

public class GCContentTest {

    @Test
    public void shouldCalculateGCContent() {
        String genome = "CCACCCTCGTGGTATGGCTAGGCATTCAGGAACCGGAGAACGCTTCAGACCAGCCCGGACTGGGAACCTGCGGGCAGTAGGTGGAAT";

        double gcContentPercentage = calculateGCPercentage(genome);
        assertThat(gcContentPercentage).isEqualTo(60.919540, Offset.offset(0.001d));
    }

    private double calculateGCPercentage(String genome) {
        double gcCount=0;
        for (char c : genome.toCharArray()) {
            if(isGC(c)) {
                gcCount ++;
            }
        }
        return 100.0 * gcCount/genome.length();
    }

    @Test
    public void shouldFindHighestGCCOntent() throws Exception {
        String inputGenomes=">Rosalind_5562\n" +
                "CCGGCCACTTTTGTCGCCCGATCGGAATGAGCACGTCAAAAGGACATCGAGAAGGAAATT\n" +
                "AGTACAGCGATTTCCCCGTCCGACGCTATTACTCTTCACCCCCCACGCAGAAATTCGAAA\n" +
                "GTGACTTGGGTATAGCAACGTTCACAAACATAATGGATCACTCTCCACGGGAGTCCAGGA\n" +
                "GACTTATTCATAGGTACCCGTTCAGGCATCCACTACCTTTAGTTTTCCCCCACGAGTCGA\n" +
                "ATTTGTATACCCGGTCTTCCCGCCTATGTGGTGACAATGAGGGTCTTGACCTGGGGGAGG\n" +
                "GGAGATCAAACCCGCATTAAGCTTCATCACTCGACAGGCGACGATCATTGACGTAATCCC\n" +
                "GGTATGTAGACGCGTATCGGTTCGATGAGTCGCTTTGCTCTCTGTCGCAACTGTACACGG\n" +
                "AGTGCCCTTCTTATCAGAGAGGCGATCCTGAGACCCGGCAAAAGTAGGAGTGACCAAGCT\n" +
                "CCAGTCACAGTGACTATCCGTAGAATGGACTGTGTATCGACTTGTCAGTGAAGTTCTGGA\n" +
                "ACTCATCCACAGACGGTTAACCACAAGTACTAGTGCCACTCGCGCACGGAGCGGGGGTTT\n" +
                "AAATTTACTAGTTCTGAACGAAAACCCCAATTAGGCGAGTTGACATTACCATTAAGTATT\n" +
                "CATTGAACGCATCAAGAGCAACCCGGTTGCGGAGCGACTAAATATGTCGCATTTCCCACG\n" +
                "GGCTCAGGTACTTGGGAAGGTTACCCTTTTCCTGGAGTCTCCACGCAACGACGTCTTAGC\n" +
                "GATTTATGTCAATTCTATAGACTTACGACACCTTAAATGTTATGCCAGAAGTTGTACACT\n" +
                "TTGTCTTAGTCGCTCCCGGTGCTACTGTACTGTTCGTTTACCGTGTAGCAAGGCTTAGGC\n" +
                "CAGGCGGTCCGACCAATGGTCCCCACT\n" +
                ">Rosalind_7384\n" +
                "AGTAGTGCGGCATTAGTACCCCCGCCAATGATACGCGTTCTTGGGATCAGACAGGCTTTG\n" +
                "CGCACGCCGCTGAATTACCTAGCGATGGGCGAGTCCCACTTGGTGCATAGGAGTCTGAGT\n" +
                "CACCTTTCGTGCTCATTAGGAGATTCAAGCCTACCGCTCACGTATCCTCTCGATAGGACG\n" +
                "CCTTACTCGGCCTCGTCTTGATAGTCAGAGTACAAAAAGGCGGCTGATCCCATGCTCCAC\n" +
                "ATATAGCCCGGCAAAGTAAAGGTTCAGCGGGTCTATGTGATGTTTATATTAGCCTATACT\n" +
                "CGGAAAGCGCTTGACCTCTACATTCAGGATTGATCCACGCGGCACGACTAGTTCTATGTT\n" +
                "AAAAAGATGAGTAGAGGTATAGATCGTACCGTTATAAACCGGAGCTGGAATGCCTACGTC\n" +
                "CGGGCGTAGTGATGCAACTGGGACGAGGAAAAAGATAAATCCCGGCCGTTTCTGCGTTGA\n" +
                "ATACTAGTCCCCCCATCGTAAAACCGTATCTTACGACACACACGTCGAGTCGGGCTGATT\n" +
                "CACTTTGGTTAAACGCTGAGCTACAAGTGTAAAGTTTATCGACGGGCGGTGAGAACCACT\n" +
                "GAGCCTAAAAGACGATGGTATTTCGCGGACAACACCCTCGCCTTCCAACTTTCCTACAGT\n" +
                "GACGGCGCGATGGTTACCGTAAGAGTCTTCCTATACTATGATCGCGAAGCCATTCGCTAA\n" +
                "TACAGGTTAGAAGTGGCCGAGACCTCAGCCACCTATAAGGATATTATATACACAAGTTCT\n" +
                "TAGGTCACCCGGTTACCACTGGAGTTTGACTTCAAGTCTGCCAGTGAGATGTATCTATTG\n" +
                "AATAACGATATAGTGTTGCCACTGATAGACCCTTTAAGACCTTATACAGACTCAATAATT\n" +
                "TACGTTCTTGACTTGACTGTCGCCCGGCTTCAGAGTGGTGGACAAGACAGACAAACAATT\n" +
                "C\n" +
                ">Rosalind_9673\n" +
                "CCGTCTGTGCGTCCTTCGAGAAAACCAGTACCTATCTAGCACAGCCGGAAGTGTCCTAGT\n" +
                "GATACTAGAAGGTCAGCACAGCAAAGGTAATCAATTCGGTCACTATCCGCACGACAACTC\n" +
                "CCTATTAAATATTATAGGACCATACCATACGGGTCAACGCTAACCACACGACTTCAAAAA\n" +
                "GTCCGCGAAAGGAAATTGCGGTTATGCAAAGGGGCCTGGAACCCAGGCCTTTACGCTCTG\n" +
                "GGAGCTTGTACTGTAATGGACGGGCCGGTACTGCTCGTCGGGCGCGGACGGACGTATTTA\n" +
                "TCGCTTCTGTCGTCAACGAAGCTGGTAGTTGCCGTGCGTGTGCCGCTCGCACTCTAATAC\n" +
                "TAGTCAAGGAGCCTATCATGTAATCTCCAGTCACGATTCGGTACGACTCCAACGTCTTCG\n" +
                "AGGTACGTAACTAATTATTCTCACGCAGTTTCCAACGGGGTGGGAACCAAATAACCTAAC\n" +
                "TACAACACCTCATTGATCGCAGGCGGCCTCCTATCCTGCAGTGAGAGAGGAAACCCTTAT\n" +
                "GCCCTTTTTCCTACAGTGAGTATGGGTGGCTATTGCCAAGAGTGCGGGACGTCTAACCGG\n" +
                "GGACCTAGATGCACCGAAGGTGATTAAAAACCCGCTAACCACTAGAAAACGCAACCACAC\n" +
                "GTCGGTTTCCCACGCGACGTAACAGCCAACCCACGTATTGCCGGCTCACTTATCAGACGA\n" +
                "ACTTTAGTATTACTTCTATAGAACGACGTGTTTAGCCAGCTCTGTCCTTAAGACTAGTGC\n" +
                "GACCCGACAGACCTTTGCGAAG\n" +
                ">Rosalind_1627\n" +
                "TGCCTCTACTAGCCGCCAGTTTCTTTAGTTTCTGATCGCTGTTACGTAACTCGCGAGCGT\n" +
                "CCTACAAACATTTATTGCGGTTGAATTGGGCTATAGATGACTGACTCTGGGGGCTCGCAC\n" +
                "CTCGGTTGTTCCGAAGGTTTCAGCGTAGAACCCCCTGGGTCCCATGGATTTCATTGGTGG\n" +
                "GAATGACCGTTTGTAAATTATAAATAGGCACTGTGAGGGAGTTAATGAGTTCTACTGTAA\n" +
                "CATAGGTGACACCTAAGTTTGCCCTAAAACCATTACATGTATTTACCTCTCTGGCATTTT\n" +
                "GATAATTTGAATAATCATACCCATATACCTAGAAGCCTCTATGATATGCTCTCCGGCCGG\n" +
                "TTTTAAGCTCCAAGTGTGGCCTGTATTGTCCAGCTACTTTTCGAACGGGTAGATGCTGTG\n" +
                "GGACTGCGCATGCAGGACTCGGAGGTTGTTGAAGGACATTTCTCGCGGGAAGCGATAGTT\n" +
                "CACTCTTCATACGGTATAAAGAATAGCGGCCCCCATCAAAGGCTACATGGGGGTAATGCC\n" +
                "GCTCTGATGCGATGCTTTTGCGTAAACGTTAGATGTAGGCCTTAAGCCCGCCTCTATGGC\n" +
                "CGGGCCACCCTGGTATGCGCGGGTTGATCGGGTGCATAAACTTCAATAATGGCCCGATGG\n" +
                "GCCACGGTTGAGGGGTAAAAGTGTTGTAGTAGCGGGAAGCGGCGTGGCGCATCAGAATAG\n" +
                "GTAGTTACTCACCCAAAGCCCTAGTCCCAAGCCTGACGTCTACAGCACCTCATCAATTTG\n" +
                "TCACGTGGACGGATAGTGGAGTTGGGCCCTCTACGGTAAGCATGTGCCCGCGGCGCTGTT\n" +
                "TAACGAGGTATGTGGTGGGGCATTGCCTTCCCGTCAGTAGAGGTCCGTTGGCGGCGGAGT\n" +
                "GGGAGTGAGGAGTTTTTCCCGCGTGGCTTTGAGAGGAAGTCCGCCTAATAAGTTGGGTAC\n" +
                "TCTCTGCTGTACGAAGTAGCACCGTCCCGCCGGTTTC\n" +
                ">Rosalind_0490\n" +
                "GCTAAAATTTCCAATACTGTACCTACCAAGTCTACCCATGTTACCAGATGCGGCGAACAT\n" +
                "GAATTTCCTAGTGGTTACTGGACGTGAGTTAGAACGAATCCGATCGTTTAGCAAGGCGGG\n" +
                "GAGATAGATTCGTGTGTCAGGAGTCTCAAGATCTCCCTCGGCGCTTTTTTCTCCTCTTCC\n" +
                "AAATCGTCACGTGGTACGCAGCGCGCCCCGGGTACAGTCAACTAGGTTATGGCTAGTGAC\n" +
                "TTTTTCACCTTTGCGCAATGACTAATGGGATTTAAGTGGCCTAAGCGACTGCTCCACAAG\n" +
                "TACGTCCCTCTTGTTTTCCTGTGAAGCATCAGGCTGTCAAGAGATAACCCGTTAGCTTTC\n" +
                "GCGTTACTAATCAGACGCATATGGGGTTGGCGCGCCGGTGGATTCTCCGACGAAAATTGC\n" +
                "GCGCATAAGCACGGAGCGTACGTCATTGCTTTAGCATAACCCATCGTAGACTTGCATCTG\n" +
                "AGGACTTTGGGAGTGGTCTTGCCGATAATGAAATGATCGGCATTACCAGCGACATTCAAA\n" +
                "TTTAGGGGCGAGCAGACGCTACCCCCCTGAAAGGTATCGTCGGAAGCGCGTTTTATCTTA\n" +
                "CATATTCAGGATGAGTCGCATCCTCCGTGCTACCGTGGGTGTGACTGCATTATTCAGGGG\n" +
                "AAGCGTTGGAGTGTATCCATATCAGTGTGAGCGTAGGTGGCCATGTGCGGGCGCTTGGAA\n" +
                "CTAGAATCCTGTCGACGCTCCGTATATCACGGATCACGGTCTGATAGTCGCTTGCTGGTG\n" +
                "CTCTACGCTGCCGGTACCTTTCTTGAAACCTTGGTGCAAGTTATCGTATACACTTCTCGG\n" +
                "ACACATCCGTAGTTAAAACATACGACTTGAGGCATAGCGATTACAAGTCTCGCTCAGAGC\n" +
                "GCACGCCGTGAATGCGTCGCGGGTCGTGAGAAGAGTGTGTGTGCTACACCAGGTCTCTAT\n" +
                "TTCTAAATAGATCTAAAATTGTCA\n" +
                ">Rosalind_4621\n" +
                "TGGAACATTGCGTCGATACAAGCGGACCACTAGTCCCTGCAACCTAGGATAGTTAGGGCA\n" +
                "CCGCTAAAGTTTAAGGATCGTGGAGCATGATGTTCCTTCGTACTCTGTCACTAGACATAC\n" +
                "GAGGAAGAGCATGGGTGTCAATCTCCCATCCGCGGTTTAAACGTGAATAACGACCCCCCG\n" +
                "ACTAAATTATAGTTCGAACACAATGGTACTGTTCCTATTGGATCGGACCACGTATATTCT\n" +
                "CGCGGTGCCGCAGTTGGAATAAATGCATATGCCCGTACTTTCCAGGTGGCCTATGTTGGT\n" +
                "ATCGCCATGAGTGGATTGGCTTATCTCCTCCGGGGACACCCGAATATTTTAATGAGCTGT\n" +
                "TGGTCCTGGGTTTGAGACTAAACGGATTTGCAAAGAGGCATGATCACCAGGACGCACGTA\n" +
                "GAACGCTACTCGGTGCCACCCCGTATCGCGGCGGGGACGGAAGTTGAGGTTGAATGTAAA\n" +
                "TCGTAGTGCAGAGGACAACGCCCAACCGTGCGGCCTCAGAGTTGGGCACCTGTCCTCGCG\n" +
                "ACGCGCTAATCGGGGTTATAAAAGGGAACCGCGGCAGCGAAAGCGCTTTGCTCCCCGGCC\n" +
                "CCGTACCGCCCGTACCTCAGATCCATGTTCCCGTTACATGCCACTGGCTGTAATGGCATA\n" +
                "CCAGCATACTAGAGCCGATCATCATGCTCGTAAGAAAACGACACACCGTTGGCTTATGCT\n" +
                "AGTGTACGCTCATGAGTCCTCCAAAGTGCTCCACAGAAACACGTCGGCGTGTCTCCTTGG\n" +
                "AGCCGGATGTCGCTAACCACGCATGTAGCCAGCTGAGCGTAAAGGAGCGTATGGTGTTAT\n" +
                "TTTCGGAAACTTACTAGCGTCTCCAACAAATCGCGTACCGAGTCAAGCTGATGACCGGGT\n" +
                "TCACCTATTAGCTTTGGTCGCTCGTTGTCCCCCGTGTGACTCGTTCAG\n" +
                ">Rosalind_5640\n" +
                "GCTCTAGGTGACCTGAGCCCATCGACTATGGAAGGGAGAGACGTAGAGACGGTACCCACC\n" +
                "AACCCAATATGTGGTCTAACATAATGCTTTTCGAACCCTTCTGGTTAGTTTGACGCATGG\n" +
                "GGCGACTACCATCCCGCCTACTTGGGGCCAGGCCGAACAAGAACGTCTGCTATCTTAGTA\n" +
                "GGTAATACGCTTAACCTTCAAGACGAAAGCAGACCGGCGAGGGCCACTAACGTAGACGGG\n" +
                "ATACCCTATTGAGTCTTTACTCGCATCATTGCATCTTCAAGATAATCACTAGGTGTCATA\n" +
                "TGACACGTATACTATAAGTGTCCGATCGTCGCACCGTCACTTCGGATGAAGAAAACGTTG\n" +
                "CGGGTTATAGAGGCTCAAAGACTCTCCAGGGGGGGCCAGGCAAGCGTAGGCTTTGCCAAA\n" +
                "GCCGCCCGCTTGTCGTATTGAAGCTGAAATTTTCGATCGCGCGTAATTCTATCTGGGCCA\n" +
                "TGGTACGCATAATGTTGAAACTATGGCCTAGCAAAGTGCGCAGGCCGCTTCCTTCGTATT\n" +
                "CCTTAGACCGCTTGGTACCAAGAGCGGATTCACTCTATTATGTATCTGGGGCCATTGGGT\n" +
                "CTTGAGGTCGAGGCTAGACGTCTTACACGCCGACGGTCCTCCTGTAAAGATTGAGCCTCC\n" +
                "TTACATCCTAAGTAAAAAGGAGAGAATATTAAGGTAACAGAAACTCGCCTATGACTCAAA\n" +
                "TGCCGGGTTCAAGGCTTGCCGTGGCACGGCAGTACAATTACCAAGCGTTTATTAATGGAG\n" +
                "CGCTCCAATAAGCGGCGCATACAGCGTAATTATTCGGGATTTGGCGTCATTCTAGGGGTG\n" +
                "TAAGACCGTCCACAGGGATGCTTTTTTGAGGATGGTCGGAATTGTCTGTTGGACTCGTAT\n" +
                "GCTCCTGTGTGGTAGGACGGGACTAGGACCTCAAAC\n" +
                ">Rosalind_7466\n" +
                "GACGGAACCCTTCGGCTCGAGATTATTTTATCTAACATAGGTTGCCGTGGGTAATTTAGA\n" +
                "TGTCTCACAACCGGTCATACTTCATCGACTGCGTAGAGAGGGTCATTTATGATGGCTTGG\n" +
                "TTCCTGGCTATTTCCGACGAAACGGCGGCCTATAAGGTGCCATTATTAAAACGGTACACT\n" +
                "ATAGAGCCCACGACTGGTCGAGTTGCCAAGGTCCTCGCTCGGCGGCTCAATGTGTTGGGA\n" +
                "CCGCTTCGCGCGATCTCGGCCGATTAAGCAGCCCGAGAACAAGAACGTAACTATGGGCTG\n" +
                "TCACACACCCACCATCATGGGGCCGAACAGGGTAACTGAGAGGTTAGCACCGTACGTGTA\n" +
                "AGGTGGTTATAGCATTGTGATCGAGACATGCGCATAGGGAACTGATGGAGAACTAGATCC\n" +
                "CATTGTTGATTTCACGGTGGATCGGCCGTCCAGGGGGCGGTCACTCAAGGTACATTGTCC\n" +
                "GCGTCACGGAGGGGTTCTTACCGACTTCTAACATCTGTATCATTAATCTTGTACGATCTC\n" +
                "CTCATATCGCAAGAGGGCGTTTAGAACAGCGCGGCAATAGCCCACAGTTTAAGATGCATT\n" +
                "GCGCACCCCAGGTACTCCGATCTCAGTTGTGTGACACCACAAGTGACATATGGGAGTGAA\n" +
                "CGAACGGTCGTGGTTTACAGAATCATATATATGGTAACCAGTAGTAAGATTGGATGTGAT\n" +
                "GAATGCATACCCCGAGCGCAAGAAAGGTATGTAAAGGAGTGCTGTTCTAAGGCGTTGAAG\n" +
                "ATGACCTGGTATATGTTAGTTACCACTATAAACGTGCGTGCAAACTAGCACCAGTAAGCC\n" +
                "GATGTTGACCCAAATCTGCGTGCCGCTACGAATAACCTGGAAATTTCACATAACCAATAC\n" +
                "TTCATTAGGCACGGTTTTTCTCTTGTATCCATCAATATGCCATACCGTTTCGAAT\n" +
                ">Rosalind_4864\n" +
                "CCGTTTCGTATGCATCGGCATACGGTCTTTACATGTCCATAAGTCAACTCGACTGACAGT\n" +
                "CCACTTATGAGAACAGTAAATCGCATCTGTGTCTAATAATCTCACGGTCCGTACCGTCTC\n" +
                "CCTTCTTGTCCGACTGCGGCGAGACGAACCGCCACCTGCACGAGGGGAGTACTTTAGCTT\n" +
                "GTGGGCTGGTTCGATTGTCGGTTAAATTGGGCCAAGTATAATTGCAGCATACATCTGCGG\n" +
                "GATGCGTATAGCCGAGGTTTGTGGTCGATGATGCGGTAAAGCTCGTGTAGGCACTACGAC\n" +
                "GTCTTGTTTGTCAACTGTTGACCGTTTGAGAGAGGCTGTCAAGTTATTCAACCCACATAT\n" +
                "ATGGCTCTAACCCCATCGCGTCCCAGCCGCATGAGAATGCGACCAATTCGCGTTTTTGGT\n" +
                "ACTTTCAACGGGAGGCAATATGCCTCTTAGATACAAACAGCAGCCGTGTTTAGCTTGACT\n" +
                "TTCAAGGATAGTGCGGTGCCAGGTTCGGGCGAATTAAGGTCTTTAAACAAAGTCGCACAT\n" +
                "GTCCTGGCGAACTTTGAGTTCTTAGGGCAACCGGTGCGCTCGGGGTCACTATTGCGTAGT\n" +
                "GAGTGCTCCCCGCCTTGGCATAGGAAGCGAATTTGTTCGTCTCTCCGACACCTCGGGGAC\n" +
                "AAAGAGGATCCAGGGGCGGTTTGAGGCGGTCCGCCTATTGGGCCAACTAGGTGCCTTCCG\n" +
                "ACAAAGCCATCGGGTGATCTGCTTATGTCCCACAATATCGAGCCCAGCGTAGGACGCTAC\n" +
                "GTGTTCAGTATACTTTTCGAAGGGTGATTGCTTGCGTAGAGGGGG\n" +
                ">Rosalind_3751\n" +
                "GATTGATTGCTATGACCTTGTCCCGCACGATCACTTCGTTCACCCACTAGACAGTAGGGA\n" +
                "TGCGGGTTGAGCATCCTACTACGAGTTTTGCAGGCACTCGTGTTGGCCGCAAATTAATTC\n" +
                "GCTCCTATATTAATCCACCTGTATAGATTTTCAAGTTTTCCAGCCTTGCTCCGCTCGTTG\n" +
                "TAGTCCAAAAACAGGTACCTACGATATAGCAGTAACGGGTACTACCTACCCGGCGGCTAC\n" +
                "TAGGGTTAACGCCAATGCATTTATTTTCGTCTCGGATCCGCGGAAGATGATCATCGTGCA\n" +
                "AACTGCGCTAGTAAGCTAACGGTGATACTGGTAAAGATGATAGGTCTCGTAGACTGGCGC\n" +
                "AAACCGTAGAATTGCAGTGATTTACCAAGCTACGCTATACCACCTGAGTGGTACATAGCG\n" +
                "CCATGATAGAATTCATATCTCCGTAGGTACTTCGTGGATCCTAGGTGCACCTTGCCAGGA\n" +
                "CGCATTGTCTCAATCCATTAGAAGCGGAAAAACTAAAAACCAGTGACAAGGTCATGAATC\n" +
                "CGAAATTGATCTTAGCCGCACGTGTTTGGCGCTTAATGCCCCCGATGGGATAATAACCAG\n" +
                "GGCGTTCGGTTAGATTTTCCGGTAGTGATTCTGTAGAATCGGCACATTCATTTCGTCCCT\n" +
                "ACGGATGCTGTGGACGCTTGCTCAAGGCCGATCCCTCAGAGAGTTGGAGGATCCGCCGGA\n" +
                "GTGTAACTTATGATAGTCCGCGTGTAATTCATTGGGCAGTAATCCATGGAGCCTGATTGA\n" +
                "CACGTCGATTGACCAATACCGTAGTGACAACCGCT";

        String[] genomes = inputGenomes.split(">");
        double max = 0d;
        String maxName="";
        for (String genomeInfo : genomes) {
            String genome = replace(substringAfter(genomeInfo, "\n"), "\n", "");
            if(calculateGCPercentage(genome)>max) {
                max = calculateGCPercentage(genome);
                maxName = substringBefore(genomeInfo, "\n");
            }
        }

        String response = maxName + "\n" + max;
        System.out.println(response);
        assertThat(response).startsWith("Rosalind_4621\n");
        assertThat(Double.valueOf(substringAfter(response,"\n"))).isEqualTo(52.53164556962025,Offset.offset(0.001));
    }

    private boolean isGC(char c) {
        return c =='G' || c== 'C';
    }

}
